version: '3'

services: 
    onnx-ecosystem:
        build:
            context: ./docker/onnx-dev/
            dockerfile: Dockerfile
        image: onnx-dev:1
        container_name: onnx-ecosystem
        volumes:
            - ./:/home/mlpipe_production
        networks: 
            - development
        ports:
            - "8888:8888"

networks:
    development: 